apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: jtallent2019/capstone:version1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
